# OpenROAD flow for ctrl_decode (single-port ASAP7) generated by OpenRoadTclGenerator
# width=10.000 height=31.320 platform=/nonexistent/platform/asap7

if {[catch {set openroad_version [openroad -version]}]} { puts "OpenROAD version check skipped" }

read_liberty @REPO_ROOT@/tech/lib/asap7sc7p5t_AO_RVT_TT.lib
read_liberty @REPO_ROOT@/tech/lib/asap7sc7p5t_INVBUF_RVT_TT.lib
read_liberty @REPO_ROOT@/tech/lib/asap7sc7p5t_OA_RVT_TT.lib
read_liberty @REPO_ROOT@/tech/lib/asap7sc7p5t_SEQ_RVT_TT.lib
read_liberty @REPO_ROOT@/tech/lib/asap7sc7p5t_SIMPLE_RVT_TT.lib
read_lef @REPO_ROOT@/tech/lef/asap7_tech.lef
read_lef @REPO_ROOT@/tech/lef/asap7sc7p5t_28_R.lef
read_verilog @SYN_ROOT@/tmp/syn_TS/netlist.v
link_design ctrl_decode

read_sdc @SYN_ROOT@/tmp/syn_TS/timing.sdc
source @REPO_ROOT@/tech/setRC.tcl
puts "Loaded ASAP7 layer, signal, clock, and via RC"

set pre_paths [find_timing_paths -path_delay max -group_path_count 20]
if {[llength $pre_paths] == 0} { error "PERIPHERY_STA: no constrained timing paths after read_sdc" }
set sdel_paths [find_timing_paths -from [get_ports -quiet {sdel*}] -path_delay max -group_path_count 4]
if {[llength $sdel_paths] < 4} { error "PERIPHERY_STA: not all sdel inputs reach sequential timing endpoints" }
check_setup -verbose > pre_place_setup.rpt

initialize_floorplan -die_area "0 0 10.000 31.320" -core_area "0 0 10.000 31.320" -site asap7sc7p5t
catch {source "/nonexistent/platform/asap7/make_tracks.tcl"} ; puts "tracks sourced or skipped"
catch {source "@REPO_ROOT@/tech/make_tracks.tcl"} ; puts "tech tracks sourced or skipped"
make_tracks M1 -x_offset 0 -y_offset 0 -x_pitch 0.036 -y_pitch 0.036
make_tracks M2 -x_offset 0 -y_offset 0 -x_pitch 0.036 -y_pitch 0.036
make_tracks M3 -x_offset 0 -y_offset 0 -x_pitch 0.036 -y_pitch 0.036
make_tracks M4 -x_offset 0 -y_offset 0 -x_pitch 0.048 -y_pitch 0.048
make_tracks M5 -x_offset 0 -y_offset 0 -x_pitch 0.048 -y_pitch 0.048
place_pins -hor_layers M4 -ver_layers M5

add_global_connection -net VDD -pin_pattern {^VDD$} -power
add_global_connection -net VSS -pin_pattern {^VSS$} -ground
global_connect

set_voltage 0.7
tapcell -distance 14 -tapcell_master TAPCELL_ASAP7_75t_R

set physical_delay_cells [get_cells -hierarchical -quiet {physical_delay_*}]
if {[llength $physical_delay_cells] != 108} { error "PERIPHERY_STRUCTURE: expected 108 named physical delay inverters, found [llength $physical_delay_cells]" }
set physical_delay_inputs [get_cells -hierarchical -quiet {physical_delay_input_*}]
if {[llength $physical_delay_inputs] != 8} { error "PERIPHERY_STRUCTURE: expected 8 named delay-chain inputs, found [llength $physical_delay_inputs]" }
set wordline_driver_cells [get_cells -hierarchical -quiet {g_bank_logic*.u_wl*_driver}]
if {[llength $wordline_driver_cells] != 64} { error "PERIPHERY_STRUCTURE: expected 64 dedicated wordline drivers, found [llength $wordline_driver_cells]" }
set_dont_touch $physical_delay_cells

global_placement -density 0.70
estimate_parasitics -placement
repair_design -max_utilization 90 -slew_margin 10 -cap_margin 10 -verbose
detailed_placement
optimize_mirroring
check_placement -verbose -report_file_name placement_check.rpt

unset_dont_touch $physical_delay_inputs
clock_tree_synthesis -clk_nets {clk} -root_buf BUFx4_ASAP7_75t_R -buf_list {BUFx2_ASAP7_75t_R BUFx4_ASAP7_75t_R BUFx8_ASAP7_75t_R} -wire_unit 20
set_propagated_clock [get_clocks {clk}]
repair_clock_nets -max_wire_length 20
set_dont_touch $physical_delay_inputs
estimate_parasitics -placement
repair_timing -setup -max_utilization 90 -max_buffer_percent 20
repair_timing -hold -max_utilization 90 -max_buffer_percent 20
detailed_placement -incremental
check_placement -verbose -report_file_name placement_post_cts.rpt

filler_placement "FILLER_ASAP7_75t_R FILLERxp5_ASAP7_75t_R"
global_route
detailed_route -output_drc detailed_route_drc.rpt

estimate_parasitics -global_routing
set final_paths [find_timing_paths -path_delay max -group_path_count 100]
if {[llength $final_paths] == 0} { error "PERIPHERY_STA: no constrained post-route timing paths" }
set final_delay_cells [get_cells -hierarchical -quiet {physical_delay_*}]
if {[llength $final_delay_cells] != 108} { error "PERIPHERY_STRUCTURE: delay topology changed during implementation" }
foreach cell $final_delay_cells { if {[get_property $cell ref_name] ne "INVx1_ASAP7_75t_R"} { error "PERIPHERY_STRUCTURE: physical delay cell was resized" } }
set final_wordline_drivers [get_cells -hierarchical -quiet {g_bank_logic*.u_wl*_driver}]
if {[llength $final_wordline_drivers] != 64} { error "PERIPHERY_STRUCTURE: wordline driver stage missing after implementation" }
foreach cell $final_wordline_drivers { if {![string match "BUF*" [get_property $cell ref_name]]} { error "PERIPHERY_STRUCTURE: non-buffer cell used as dedicated wordline driver" } }
set structure_fd [open periphery_implementation.rpt w]
puts $structure_fd "physical_delay_invx1 [llength $final_delay_cells]"
puts $structure_fd "dedicated_wordline_buffers [llength $final_wordline_drivers]"
puts $structure_fd "constrained_max_paths [llength $final_paths]"
close $structure_fd
report_checks -path_delay min_max -fields {slew capacitance fanout input_pin net} -digits 4 > timing.rpt
report_checks -to [get_ports -quiet {wlt* wlb*}] -path_delay min_max -fields {slew capacitance fanout input_pin net} -digits 4 > wordline_timing.rpt
report_check_types -max_slew -max_capacitance -max_fanout -violators -verbose > electrical.rpt
check_setup -verbose > final_setup.rpt
report_clock_properties > clock_properties.rpt
report_clock_skew -setup > clock_skew.rpt
report_design_area > design_area.rpt
report_tns -max
report_wns -max
if {[file size electrical.rpt] == 0} { set electrical_empty_fd [open electrical.rpt w]; puts $electrical_empty_fd "PASS: no max slew, capacitance, or fanout violations."; close $electrical_empty_fd }
set electrical_fd [open electrical.rpt r]
set electrical_text [read $electrical_fd]
close $electrical_fd
if {[string first "(VIOLATED)" $electrical_text] >= 0} { error "PERIPHERY_STA: max slew/capacitance/fanout violations remain" }
set setup_slack [worst_slack -max]
set hold_slack [worst_slack -min]
if {$setup_slack < -0.001} { error "PERIPHERY_STA: setup timing violation $setup_slack ns" }
if {$hold_slack < -0.001} { error "PERIPHERY_STA: hold timing violation $hold_slack ns" }
puts "PERIPHERY_STA_PASS paths=[llength $final_paths] setup_slack=$setup_slack hold_slack=$hold_slack"

# Expected M3 pins for stacked_colgrp (handled by LayoutGenerator):
#   WLT[31:0] WLB[31:0] at M3 y=[-0.15,31.470]
#   blprechtn/yseltn/yselt/wrena/saprechn/sae/wrenan etc. per col_width=9.396

write_def ctrl_decode.def
write_verilog netlist_for_lvs.v
write_sdc ctrl_decode.sdc
catch {write_db ctrl_decode.odb}
exit
