#!/usr/bin/env python3
"""Generate the ASAP7 8T port-A and port-B IO/precharge wrappers.

Both wrappers reuse the published differential ``iocolgrp_sram_6t122_v2``
hard core.  A pitch adapter expands its four 6T bitline-pair landings to the
four-row 8T array pitch generated by ``generate_asap7_8t_bitcell.py``.

Port A presents its array interface on M2.  Port B presents the same logical
interface on M4 and drops to the M2 inputs of the reused IO core through
M4/V3/M3/V2.  Sense enable, sense precharge, bitline precharge, column select,
write, and output-enable controls remain independent between the two cells.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import re
import sys
from collections import Counter
from pathlib import Path

import gdstk


SOURCE_CELL = "iocolgrp_sram_6t122_v2"
BITCELL_NAME = "sram_cell_8t"
CELL_NAMES = ("ioprech_sram_8t_a", "ioprech_sram_8t_b")
FIXED_GDS_TIMESTAMP = dt.datetime(2020, 1, 1, 0, 0, 0)

V2 = 25
M2 = 20
M3 = 30
V3 = 35
M4 = 40
BOUNDARY = 100
PIN_TEXTTYPE = 251

MUX_ROWS = 4
CORE_WIDTH = 2.376
CORE_HEIGHT = 1.080
# Eight independent M3 risers use every other 36 nm routing track.  The wider
# 72 nm pitch leaves legal same-layer clearance between neighboring M2 route
# endcaps and keeps the risers outside the flattened active-cell geometry.
RISER_PITCH = 0.072
ADAPTER_WIDTH = 0.684
WRAPPER_WIDTH = CORE_WIDTH + 2 * ADAPTER_WIDTH
CORE_X = ADAPTER_WIDTH

# Center the source core's BOUNDARY (y=0.0135..1.0935) in four 8T rows.
SOURCE_BOUNDARY_Y0 = 0.0135
CORE_Y = ((2.376 - CORE_HEIGHT) / 2) - SOURCE_BOUNDARY_Y0


def rect(cell: gdstk.Cell, box: tuple[float, float, float, float], layer: int) -> None:
    x0, y0, x1, y1 = box
    cell.add(gdstk.rectangle((x0, y0), (x1, y1), layer=layer, datatype=0))


def bbox(poly: gdstk.Polygon) -> tuple[float, float, float, float]:
    (x0, y0), (x1, y1) = poly.bounding_box()
    return tuple(round(float(v), 7) for v in (x0, y0, x1, y1))


def clone_label(label: gdstk.Label, text: str, origin=None, layer=None) -> gdstk.Label:
    return gdstk.Label(
        text,
        tuple(origin if origin is not None else label.origin),
        anchor=label.anchor,
        rotation=label.rotation,
        magnification=label.magnification,
        x_reflection=label.x_reflection,
        layer=label.layer if layer is None else layer,
        texttype=PIN_TEXTTYPE,
    )


def boundary_box(cell: gdstk.Cell) -> tuple[float, float, float, float]:
    boundaries = [bbox(poly) for poly in cell.polygons
                  if poly.layer == BOUNDARY and poly.datatype == 0]
    if len(boundaries) != 1:
        raise RuntimeError(f"{cell.name}: expected one BOUNDARY polygon")
    return boundaries[0]


def direct_labels(cell: gdstk.Cell) -> dict[str, gdstk.Label]:
    labels: dict[str, gdstk.Label] = {}
    for label in cell.labels:
        if label.text in labels and not label.text.lower().startswith(("vdd", "vss")):
            raise RuntimeError(f"{cell.name}: duplicate direct label {label.text!r}")
        labels[label.text] = label
    return labels


def bitline_pin_y(bitcell: gdstk.Cell, port: str) -> dict[str, list[float]]:
    """Return true/complement pin centers for four alternating array rows."""
    labels = direct_labels(bitcell)
    true_name, comp_name = (("BLA", "BLAN") if port == "A" else ("BLB", "BLBN"))
    if true_name not in labels or comp_name not in labels:
        raise RuntimeError(f"{bitcell.name}: missing {port}-port bitline labels")

    _x0, y0, _x1, y1 = boundary_box(bitcell)
    pitch = y1 - y0
    normalized = {
        "bl": float(labels[true_name].origin[1]) - y0,
        "bln": float(labels[comp_name].origin[1]) - y0,
    }
    result = {"bl": [], "bln": []}
    for row in range(MUX_ROWS):
        for kind, local_y in normalized.items():
            if row % 2 == 0:
                y = row * pitch + local_y
            else:
                y = (row + 1) * pitch - local_y
            result[kind].append(round(y, 7))
    return result


def rename_core_pin(name: str, port: str) -> str | None:
    scalar = {
        "WD": f"D_{port}",
        "wrena": f"WRENA_{port}",
        "wrenan": f"WRENAN_{port}",
        "SAE": f"SAE_{port}",
        "SAPRECHN": f"SAPRECHN_{port}",
        "saob": f"Q_{port}",
        "en_out": f"OE_OUT_{port}",
        "enb_out": f"OEB_OUT_{port}",
        "BLPRECHTN": f"BLPRECHTN_{port}",
        "BLPRECHBN": f"BLPRECHBN_{port}",
    }
    if name in scalar:
        return scalar[name]
    if name.lower().startswith("vdd"):
        return "VDD"
    if name.lower().startswith("vss"):
        return "VSS"

    match = re.fullmatch(r"(yseltn|yselt|yselbn|yselb)<([0-3])>", name)
    if match:
        return f"{match.group(1).upper()}_{port}[{match.group(2)}]"
    return None


def core_bitline_name(name: str, port: str) -> str | None:
    match = re.fullmatch(r"(bltn|blt|blbn|blb)<([0-3])>", name)
    if not match:
        return None
    return f"{match.group(1).upper()}_{port}[{match.group(2)}]"


def add_m2_to_m3_route(
    cell: gdstk.Cell,
    side: str,
    riser_x: float,
    external_y: float,
    target_x: float,
    target_y: float,
) -> list[tuple[int, tuple[float, float, float, float]]]:
    """Route an M2 array pin through an M3 pitch-shifting riser."""
    shapes: list[tuple[int, tuple[float, float, float, float]]] = []

    def add(box: tuple[float, float, float, float], layer: int) -> None:
        rect(cell, box, layer)
        shapes.append((layer, box))

    if side == "left":
        add((0.0, external_y - 0.009, riser_x + 0.014,
             external_y + 0.009), M2)
    else:
        add((riser_x - 0.014, external_y - 0.009, WRAPPER_WIDTH,
             external_y + 0.009), M2)
    add((min(riser_x, target_x) - 0.014, target_y - 0.009,
         max(riser_x, target_x) + 0.014, target_y + 0.009), M2)
    add((riser_x - 0.009, min(external_y, target_y) - 0.014,
         riser_x + 0.009, max(external_y, target_y) + 0.014), M3)
    for y in (external_y, target_y):
        add((riser_x - 0.009, y - 0.009,
             riser_x + 0.009, y + 0.009), V2)
    return shapes


def add_m4_to_m2_route(
    cell: gdstk.Cell,
    side: str,
    riser_x: float,
    external_y: float,
    target_x: float,
    target_y: float,
) -> list[tuple[int, tuple[float, float, float, float]]]:
    """Route an M4 array pin through M3 to the reused core's M2 pin."""
    shapes: list[tuple[int, tuple[float, float, float, float]]] = []

    def add(box: tuple[float, float, float, float], layer: int) -> None:
        rect(cell, box, layer)
        shapes.append((layer, box))

    if side == "left":
        add((0.0, external_y - 0.012, max(riser_x + 0.020, 0.096),
             external_y + 0.012), M4)
    else:
        add((min(riser_x - 0.020, WRAPPER_WIDTH - 0.096),
             external_y - 0.012, WRAPPER_WIDTH,
             external_y + 0.012), M4)
    add((min(riser_x, target_x) - 0.014, target_y - 0.009,
         max(riser_x, target_x) + 0.014, target_y + 0.009), M2)
    add((riser_x - 0.009, min(external_y, target_y) - 0.014,
         riser_x + 0.009, max(external_y, target_y) + 0.014), M3)
    # The vertical M3 riser remains the same 18 nm width as V2.  At V3, add a
    # 28 x 24 nm horizontal landing so V3 has 5 nm M3 endcaps while retaining
    # the via's exact 24 nm width perpendicular to that local M3 segment.
    add((riser_x - 0.014, external_y - 0.012,
         riser_x + 0.014, external_y + 0.012), M3)
    add((riser_x - 0.009, target_y - 0.009,
         riser_x + 0.009, target_y + 0.009), V2)
    add((riser_x - 0.009, external_y - 0.012,
         riser_x + 0.009, external_y + 0.012), V3)
    return shapes


def validate_adapter_spacing(
    routes: dict[str, list[tuple[int, tuple[float, float, float, float]]]]
) -> None:
    """Reject same-layer shorts or sub-minimum spacing between adapter nets."""
    spacing = {M2: 0.018, V2: 0.018, M3: 0.018, V3: 0.018, M4: 0.024}
    names = list(routes)
    for i, name in enumerate(names):
        for other_name in names[i + 1:]:
            for layer, a in routes[name]:
                for other_layer, b in routes[other_name]:
                    if layer != other_layer:
                        continue
                    ax0, ay0, ax1, ay1 = a
                    bx0, by0, bx1, by1 = b
                    dx = max(ax0 - bx1, bx0 - ax1, 0.0)
                    dy = max(ay0 - by1, by0 - ay1, 0.0)
                    required = spacing[layer]
                    if dx == 0.0:
                        okay = dy >= required - 1e-9
                    elif dy == 0.0:
                        okay = dx >= required - 1e-9
                    else:
                        okay = (dx * dx + dy * dy) ** 0.5 >= required - 1e-9
                    if not okay:
                        raise RuntimeError(
                            f"adapter spacing violation on layer {layer}: "
                            f"{name} vs {other_name}"
                        )


def copy_flat_core(source: gdstk.Cell, target: gdstk.Cell) -> None:
    flat = source.copy(f"__{target.name}_flat", deep_copy=True)
    flat.flatten()
    for poly in flat.polygons:
        if poly.layer == BOUNDARY:
            continue
        points = [(float(x) + CORE_X, float(y) + CORE_Y) for x, y in poly.points]
        target.add(gdstk.Polygon(points, layer=poly.layer, datatype=poly.datatype))


def assign_riser_order(entries: list[dict]) -> dict[str, int]:
    """Channel-route close external/internal M2 tracks without same-layer shorts.

    If one net's external horizontal is within one M2 pitch of another net's
    internal horizontal, the former riser must be closer to the array edge.
    The resulting dependency graph is acyclic for both 8T port interfaces.
    """
    count = len(entries)
    adjacency: list[list[int]] = [[] for _ in range(count)]
    indegree = [0] * count
    for i, entry in enumerate(entries):
        for j, other in enumerate(entries):
            if i == j or abs(entry["external_y"] - other["target_y"]) >= 0.036:
                continue
            adjacency[i].append(j)
            indegree[j] += 1

    ready = [index for index, degree in enumerate(indegree) if degree == 0]
    order: list[int] = []
    while ready:
        index = ready.pop(0)
        order.append(index)
        for follower in adjacency[index]:
            indegree[follower] -= 1
            if indegree[follower] == 0:
                ready.append(follower)
                ready.sort()
    if len(order) != count:
        raise RuntimeError("8T pitch adapter has cyclic M2 channel-routing constraints")
    return {entries[index]["source_name"]: rank for rank, index in enumerate(order)}


def build_wrapper(
    source: gdstk.Cell, bitcell: gdstk.Cell, port: str
) -> gdstk.Cell:
    cell = gdstk.Cell(f"ioprech_sram_8t_{port.lower()}")
    copy_flat_core(source, cell)

    bit_y = bitline_pin_y(bitcell, port)
    source_labels = direct_labels(source)

    # Preserve the source IO core's non-bitline pins with explicit port names.
    for label in source.labels:
        renamed = rename_core_pin(label.text, port)
        if renamed is None:
            continue
        cell.add(clone_label(
            label,
            renamed,
            (float(label.origin[0]) + CORE_X,
             float(label.origin[1]) + CORE_Y),
        ))

    route_specs: list[tuple[str, str, int, str]] = []
    for side, prefix in (("left", "blt"), ("right", "blb")):
        for index in range(MUX_ROWS):
            route_specs.extend((
                (side, f"{prefix}n<{index}>", index, "bln"),
                (side, f"{prefix}<{index}>", index, "bl"),
            ))

    route_entries: list[dict] = []
    for side, source_name, row, kind in route_specs:
        label = source_labels.get(source_name)
        if label is None:
            raise RuntimeError(f"{source.name}: missing bitline pin {source_name}")
        route_entries.append({
            "side": side,
            "source_name": source_name,
            "row": row,
            "kind": kind,
            "external_y": bit_y[kind][row],
            "target_x": float(label.origin[0]) + CORE_X,
            "target_y": float(label.origin[1]) + CORE_Y,
            "label": label,
        })
    riser_orders = {
        side: assign_riser_order(
            [entry for entry in route_entries if entry["side"] == side]
        )
        for side in ("left", "right")
    }

    pin_layer = M2 if port == "A" else M4
    adapter_routes: dict[str, list[tuple[int, tuple[float, float, float, float]]]] = {}
    for entry in route_entries:
        side = entry["side"]
        source_name = entry["source_name"]
        label = entry["label"]
        route_index = riser_orders[side][source_name]
        # Port B needs 11 nm M4 endcaps around its 18 nm-wide V3.  Keep its
        # outer riser center 20 nm from the boundary so the edge-facing
        # endcap is not clipped; port A has no V3/M4 transition.
        edge_offset = 0.018 if port == "A" else 0.020
        if side == "left":
            riser_x = edge_offset + route_index * RISER_PITCH
            pin_x = 0.006
        else:
            riser_x = WRAPPER_WIDTH - edge_offset - route_index * RISER_PITCH
            pin_x = WRAPPER_WIDTH - 0.006
        external_y = entry["external_y"]
        target_x = entry["target_x"]
        target_y = entry["target_y"]

        if port == "A":
            shapes = add_m2_to_m3_route(
                cell, side, riser_x, external_y, target_x, target_y
            )
        else:
            shapes = add_m4_to_m2_route(
                cell, side, riser_x, external_y, target_x, target_y
            )

        pin_name = core_bitline_name(source_name, port)
        if pin_name is None:
            raise RuntimeError(f"cannot rename {source_name}")
        adapter_routes[pin_name] = shapes
        cell.add(clone_label(label, pin_name, (pin_x, external_y), pin_layer))

    validate_adapter_spacing(adapter_routes)
    wrapper_height = (boundary_box(bitcell)[3] - boundary_box(bitcell)[1]) * MUX_ROWS
    rect(cell, (0.0, 0.0, WRAPPER_WIDTH, wrapper_height), BOUNDARY)
    return cell


def build_library(source_gds: Path, bitcell_gds: Path) -> gdstk.Library:
    source_lib = gdstk.read_gds(str(source_gds))
    bitcell_lib = gdstk.read_gds(str(bitcell_gds))
    source = next((cell for cell in source_lib.cells if cell.name == SOURCE_CELL), None)
    bitcell = next((cell for cell in bitcell_lib.cells if cell.name == BITCELL_NAME), None)
    if source is None:
        raise RuntimeError(f"{SOURCE_CELL!r} not found in {source_gds}")
    if bitcell is None:
        raise RuntimeError(f"{BITCELL_NAME!r} not found in {bitcell_gds}")
    if boundary_box(source) != (0.0, 0.0135, 2.376, 1.0935):
        raise RuntimeError(f"{SOURCE_CELL}: source IO boundary changed")
    if boundary_box(bitcell) != (0.0, -0.162, 0.108, 0.432):
        raise RuntimeError(f"{BITCELL_NAME}: 8T bitcell boundary changed")

    lib = gdstk.Library(
        "openfinram_asap7_8t_ioprech",
        unit=source_lib.unit,
        precision=source_lib.precision,
    )
    lib.add(build_wrapper(source, bitcell, "A"))
    lib.add(build_wrapper(source, bitcell, "B"))
    return lib


def polygon_record(poly: gdstk.Polygon) -> tuple:
    points = tuple((round(float(x), 6), round(float(y), 6)) for x, y in poly.points)
    return poly.layer, poly.datatype, points


def cell_digest(cell: gdstk.Cell) -> str:
    records: list[tuple] = [("P",) + polygon_record(poly) for poly in cell.polygons]
    records.extend(
        ("L", label.text, round(float(label.origin[0]), 6),
         round(float(label.origin[1]), 6), label.layer, label.texttype)
        for label in cell.labels
    )
    digest = hashlib.sha256()
    for record in sorted(records, key=repr):
        digest.update(repr(record).encode("utf-8"))
    return digest.hexdigest()


def _assert(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def verify_gds(path: Path) -> dict[str, str]:
    lib = gdstk.read_gds(str(path))
    cells = {cell.name: cell for cell in lib.cells}
    _assert(set(cells) == set(CELL_NAMES),
            f"expected cells {CELL_NAMES}, found {tuple(sorted(cells))}")

    expected_boundary = (0.0, 0.0, round(WRAPPER_WIDTH, 7), 2.376)
    for port, cell_name in (("A", CELL_NAMES[0]), ("B", CELL_NAMES[1])):
        cell = cells[cell_name]
        _assert(not cell.references, f"{cell_name}: wrapper must be self-contained")
        _assert(boundary_box(cell) == expected_boundary,
                f"{cell_name}: wrong four-row 8T boundary")

        labels = [label for label in cell.labels if label.texttype == PIN_TEXTTYPE]
        names = {label.text for label in labels}
        expected_scalars = {
            f"D_{port}", f"Q_{port}", f"WRENA_{port}", f"WRENAN_{port}",
            f"SAE_{port}", f"SAPRECHN_{port}", f"OE_OUT_{port}",
            f"OEB_OUT_{port}", f"BLPRECHTN_{port}", f"BLPRECHBN_{port}",
            "VDD", "VSS",
        }
        expected_indexed = {
            f"{prefix}_{port}[{index}]"
            for prefix in ("BLT", "BLTN", "BLB", "BLBN",
                           "YSELT", "YSELTN", "YSELB", "YSELBN")
            for index in range(MUX_ROWS)
        }
        _assert(names == expected_scalars | expected_indexed,
                f"{cell_name}: pin-name set does not match wrapper contract")
        _assert(any(label.text == "VDD" for label in labels),
                f"{cell_name}: missing VDD labels")
        _assert(any(label.text == "VSS" for label in labels),
                f"{cell_name}: missing VSS labels")

        bitline_labels = [label for label in labels
                          if label.text.startswith(("BLT_", "BLTN_", "BLB_", "BLBN_"))]
        expected_layer = M2 if port == "A" else M4
        _assert(len(bitline_labels) == 16,
                f"{cell_name}: expected 16 four-way-mux bitline pins")
        _assert(all(label.layer == expected_layer for label in bitline_labels),
                f"{cell_name}: bitline pins are not all on M{2 if port == 'A' else 4}")
        _assert(all(label.layer == M3 for label in labels
                    if label.text.startswith(("YSEL", "SAE_", "SAPRECHN_",
                                              "BLPRECH", "WREN", "OE_", "OEB_",
                                              "D_", "Q_"))),
                f"{cell_name}: IO/control pins must retain the source M3 interface")

        if port == "B":
            m4_boxes = [bbox(poly) for poly in cell.polygons
                        if poly.layer == M4 and poly.datatype == 0]
            v3_boxes = [bbox(poly) for poly in cell.polygons
                        if poly.layer == V3 and poly.datatype == 0]
            _assert(len(m4_boxes) == 16,
                    f"{cell_name}: expected one M4 landing per bitline")
            _assert(len(v3_boxes) == 16,
                    f"{cell_name}: expected one V3 drop per bitline")
            _assert(all((x1 - x0) * (y1 - y0) >= 0.002 - 1e-12
                        for x0, y0, x1, y1 in m4_boxes),
                    f"{cell_name}: M4 landing violates minimum area")
            for label in bitline_labels:
                x, y = map(float, label.origin)
                _assert(any(x0 <= x <= x1 and y0 <= y <= y1
                            for x0, y0, x1, y1 in m4_boxes),
                        f"{cell_name}: {label.text} is not on its M4 route")
        else:
            _assert(not any(poly.layer in (V3, M4) for poly in cell.polygons),
                    f"{cell_name}: port A unexpectedly uses the port-B upper metals")

    # Port B must contain the complete port-A core geometry plus only its
    # additional pitch-adapter shapes.  This catches accidental core drift.
    adapter_layers = {M2, V2, M3, V3, M4, BOUNDARY}
    a_records = Counter(polygon_record(poly) for poly in cells[CELL_NAMES[0]].polygons
                        if poly.layer not in adapter_layers)
    b_records = Counter(polygon_record(poly) for poly in cells[CELL_NAMES[1]].polygons
                        if poly.layer not in adapter_layers)
    missing = a_records - b_records
    _assert(not missing, "port-B wrapper does not preserve the reused IO core")
    return {name: cell_digest(cell) for name, cell in sorted(cells.items())}


def parse_args(argv: list[str]) -> argparse.Namespace:
    repo = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-gds",
        type=Path,
        default=repo / "tech/gds/srambank_32b_boundary_2.gds",
        help=f"tracked ASAP7 GDS containing {SOURCE_CELL}",
    )
    parser.add_argument(
        "--bitcell-gds",
        type=Path,
        default=repo / "tech/gds/sram_cell_8t.gds",
        help=f"generated GDS containing {BITCELL_NAME}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repo / "tech/gds/sram_8t_ioprech.gds",
        help="generated port-A/port-B IO/precharge wrapper GDS",
    )
    parser.add_argument(
        "--verify",
        type=Path,
        help="verify an existing wrapper GDS instead of generating one",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        if args.verify:
            digests = verify_gds(args.verify)
            print(f"PASS {args.verify}: {len(digests)} 8T IO/precharge wrappers")
            for name, digest in digests.items():
                print(f"  {name}: sha256={digest}")
            return 0

        lib = build_library(args.source_gds, args.bitcell_gds)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        lib.write_gds(str(args.output), timestamp=FIXED_GDS_TIMESTAMP)
        digests = verify_gds(args.output)
        print(f"wrote {args.output}: {len(digests)} 8T IO/precharge wrappers")
        for name, digest in digests.items():
            print(f"  {name}: sha256={digest}")
        return 0
    except (OSError, RuntimeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
