#pragma once

#include <string>
#include <map>
#include <vector>

namespace OpenFinRAM {

/**
 * @brief Capacitance data for a single net/pin
 */
struct CapacitanceData {
    std::string pin_name;       // Pin name (e.g., "WLT[0]", "BLPRECHTN")
    double total_cap_f;         // Total capacitance in Farads (F)
    double total_cap_pf;        // Total capacitance in picoFarads (pF)
    
    CapacitanceData() : total_cap_f(0.0), total_cap_pf(0.0) {}
};

/**
 * @brief Parser for PEX capacitance report (rep.txt)
 * 
 * Parses the capacitance report generated by Calibre PEX
 * and extracts capacitance values for each pin/net.
 */
class CapacitanceParser {
public:
    /**
     * @brief Parse capacitance report file
     * @param rep_file_path Path to rep.txt file
     * @return true if successful, false otherwise
     */
    bool parse(const std::string& rep_file_path);
    
    /**
     * @brief Get capacitance for a specific pin
     * @param pin_name Pin name to search for (case-insensitive)
     * @return Capacitance in pF, or 0.0 if not found
     */
    double get_capacitance_pf(const std::string& pin_name) const;
    
    /**
     * @brief Get all capacitance data
     * @return Map of pin names to capacitance data
     */
    const std::map<std::string, CapacitanceData>& get_all_capacitances() const {
        return capacitances_;
    }
    
    /**
     * @brief Get capacitance for pins matching a pattern
     * @param pattern Pattern to match (e.g., "WLT" matches "WLT[0]", "WLT[1]", etc.)
     * @return Vector of matching capacitance data
     */
    std::vector<CapacitanceData> get_capacitances_by_pattern(const std::string& pattern) const;
    
    /**
     * @brief Get average capacitance for pins matching a pattern
     * @param pattern Pattern to match
     * @return Average capacitance in pF, or 0.0 if no matches
     */
    double get_average_capacitance_pf(const std::string& pattern) const;
    
    /**
     * @brief Get maximum capacitance for pins matching a pattern
     * @param pattern Pattern to match
     * @return Maximum capacitance in pF, or 0.0 if no matches
     */
    double get_max_capacitance_pf(const std::string& pattern) const;
    
    /**
     * @brief Check if parser has valid data
     * @return true if data was successfully parsed
     */
    bool has_data() const { return !capacitances_.empty(); }
    
    /**
     * @brief Print summary of parsed data
     */
    void print_summary() const;

private:
    std::map<std::string, CapacitanceData> capacitances_;
    
    /**
     * @brief Normalize pin name for lookup (convert to uppercase, remove spaces)
     * @param name Original pin name
     * @return Normalized pin name
     */
    std::string normalize_pin_name(const std::string& name) const;
    
    /**
     * @brief Parse a single line from rep.txt
     * @param line Line to parse
     * @param data Output capacitance data
     * @return true if line was successfully parsed
     */
    bool parse_line(const std::string& line, CapacitanceData& data);
};

} // namespace OpenFinRAM
