#include "yosys_tcl_generator.hpp"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <sstream>

#include "plog/Log.h"
#include "utils.hpp"

namespace OpenFinRAM {

std::vector<std::string> YosysTclGenerator::resolve_liberty_files(
    const std::string& platform_path,
    const std::string& tech_lib_path) {
    // Prefer platform/asap7/lib/*.lib if directory exists, else tech/lib fallback.
    // This matches the ask: "asap7 platform pull from platform/asap7"
    std::vector<std::string> candidates = {
        "asap7sc7p5t_AO_RVT_TT.lib",
        "asap7sc7p5t_INVBUF_RVT_TT.lib",
        "asap7sc7p5t_OA_RVT_TT.lib",
        "asap7sc7p5t_SEQ_RVT_TT.lib",
        "asap7sc7p5t_SIMPLE_RVT_TT.lib",
    };
    std::vector<std::string> resolved;
    for (auto &f : candidates) {
        std::string p = join_path(platform_path + "/lib", f);
        if (file_exists(p)) {
            resolved.push_back(p);
        } else {
            std::string q = join_path(tech_lib_path, f);
            if (file_exists(q)) resolved.push_back(q);
            else resolved.push_back(q); // still emit; yosys will error clearly if missing
        }
    }
    return resolved;
}

std::string YosysTclGenerator::generate_script(
    const std::string& rtl_path,
    const std::string& syn_path,
    const std::string& param_str,
    int addr_width,
    unsigned num_wls,
    unsigned num_banks,
    unsigned num_wl_buf,
    unsigned num_sae_buf,
    double abc_load_ff,
    double abc_delay_ps,
    const std::string& platform_path,
    const std::string& tech_lib_path) const {

    auto libs = resolve_liberty_files(platform_path, tech_lib_path);
    std::ostringstream lib_list;
    for (size_t i = 0; i < libs.size(); ++i) {
        if (i) lib_list << " ";
        lib_list << libs[i];
    }

    std::ostringstream oss;
    oss << "# Yosys synthesis script for ctrl_decode (single-port ASAP7)\n";
    oss << "# Auto-generated by OpenFinRAM YosysTclGenerator\n";
    oss << "#   ADDR_WIDTH=" << addr_width << " NUM_WL=" << num_wls << " NUM_BANK=" << num_banks << "\n";
    oss << "#   platform=" << platform_path << " tech_lib=" << tech_lib_path << "\n\n";

    // Keep pre-instantiated physical timing cells opaque.  Reading the Liberty
    // functions as synthesizable logic makes an even inverter chain look like
    // an identity and allows Yosys to delete the programmable delay network.
    // ABC and dfflibmap still use the Liberty files directly for mapping/timing.
    for (auto &lib : libs) {
        if (lib.find("SEQ") != std::string::npos) {
            oss << "read_liberty -lib -ignore_miss_func -ignore_miss_data_latch " << lib << "\n";
        } else {
            oss << "read_liberty -lib " << lib << "\n";
        }
    }
    oss << "read_verilog -sv " << join_path(rtl_path, "delay_cell.v") << "\n";
    oss << "read_verilog -sv " << join_path(rtl_path, "sram_control.v") << "\n";
    oss << "chparam -set ADDR_WIDTH " << addr_width
        << " -set NUM_WL " << num_wls
        << " -set NUM_BANK " << num_banks
        << " ctrl_decode\n";
    oss << "hierarchy -check -top ctrl_decode\n";

    oss << "\n# Generic synthesis\n";
    oss << "synth -top ctrl_decode -flatten\n";
    oss << "opt\n";
    oss << "\n# Technology mapping\n";
    // dfflibmap using SEQ lib for flops
    std::string seq_lib;
    for (auto &l : libs) if (l.find("SEQ") != std::string::npos) seq_lib = l;
    if (!seq_lib.empty()) {
        oss << "dfflibmap -liberty " << seq_lib << "\n";
    }
    oss << "opt\n";
    // ABC's constraint file uses femtofarads and picoseconds.  It captures the
    // worst predicted array load so output gates are not selected as if the
    // controller were driving bare top-level ports.
    {
        oss << "abc";
        for (auto &lib : libs) oss << " -liberty " << lib;
        oss << " -constr " << join_path(syn_path, "abc.constr")
            << " -D " << std::fixed << std::setprecision(3) << abc_delay_ps
            << "\n";
    }
    oss << "opt\n";
    oss << "opt_clean -purge\n";

    // Periphery correctness gates.  The current ctrl_decode contains exactly
    // ADDR_WIDTH + four sdel + three control state bits, and four selectable
    // delay stages containing 108 explicitly instantiated INVx1 cells.
    oss << "\n# Structural signoff for the physical timing network\n";
    oss << "check -assert\n";
    oss << "select -assert-count " << (addr_width + 7)
        << " t:DFFHQNx1_ASAP7_75t_R\n";
    oss << "select -assert-min 108 t:INVx1_ASAP7_75t_R\n";
    oss << "select -assert-count 108 t:INVx1_ASAP7_75t_R a:dont_touch %i\n";
    oss << "select -assert-count 8 t:INVx1_ASAP7_75t_R a:delay_input %i\n";
    oss << "select -assert-min " << (2 * num_wls * num_banks)
        << " t:BUFx4_ASAP7_75t_R\n";

    // Give the protected delay cells stable, legal Verilog names.  OpenROAD
    // can then protect exactly this network instead of every INVx1 in the
    // mapped decoder (which prevents legitimate fanout repair elsewhere).
    oss << "rename -hide t:INVx1_ASAP7_75t_R a:delay_input %i\n";
    oss << "rename -enumerate -pattern physical_delay_input_% "
        << "t:INVx1_ASAP7_75t_R a:delay_input %i\n";
    oss << "rename -hide t:INVx1_ASAP7_75t_R a:dont_touch %i "
        << "a:delay_input %d\n";
    oss << "rename -enumerate -pattern physical_delay_% "
        << "t:INVx1_ASAP7_75t_R a:dont_touch %i a:delay_input %d\n";

    oss << "\n# Outputs\n";
    oss << "write_verilog -noattr -noexpr -nohex " << join_path(syn_path, "netlist.v") << "\n";
    // Also keep a Yosys JSON for debug
    oss << "write_json " << join_path(syn_path, "netlist.json") << "\n";
    // timing.sdc and abc.constr are generated by YosysManager.
    // QoR report via stat captured with tee (yosys tee supports `tee -o file <yosys_cmd>`)
    {
        oss << "tee -o " << join_path(syn_path, "qor_report.txt") << " stat";
        for (auto &lib : libs) oss << " -liberty " << lib;
        oss << "\n";
    }
    // Ensure Cell Area line exists for Innovus/OpenROAD parser

    oss << "# ABC output load = " << std::fixed << std::setprecision(3)
        << abc_load_ff << " fF, delay target = " << abc_delay_ps << " ps\n";
    oss << "\n# Done\n";
    return oss.str();
}

} // namespace OpenFinRAM
